#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     A,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     B,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     C,             tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     D,             tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

string direction = "up";

void initializeRobot()
{

	return;
}

task directionCont(){
	while(true){
		getJoystickSettings(joystick);
		if(joystick.joy1_TopHat == 0){
			direction = "up";
			}else if(joystick.joy1_TopHat == 2){
			direction = "right";
			}else if(joystick.joy1_TopHat == 4){
			direction = "down";
			}else if(joystick.joy1_TopHat == 6){
			direction = "left";
		}
		abortTimeslice();
	}
}

float DZ(float input){
	if(input < 15 && input > -15){
		return 0;
	}else{
		return input;
	}
}

task drive(){

	int turn;
	while(true){
		getJoystickSettings(joystick);
		if(direction == "up"){
			motor[C] = (((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*75) - turn;
			motor[D] = (((DZ(joystick.joy1_y1)-DZ(joystick.joy1_x1))/128.0)*75) - turn;
			motor[A] = -(((DZ(joystick.joy1_y1)+DZ(joystick.joy1_x1))/128.0)*75) - turn;
			motor[B] = (((DZ(joystick.joy1_x1)-DZ(joystick.joy1_y1))/128.0)*75) - turn;
			}else if(direction == "right"){
			motor[D] = ((((DZ(joystick.joy1_y1))+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[A] = ((((DZ(joystick.joy1_y1))-DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[B] = -((((DZ(joystick.joy1_y1))+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[C] = ((((DZ(joystick.joy1_x1))-DZ(joystick.joy1_y1))/128.0)*100) - turn;

			}else if(direction == "down"){
			motor[A] = ((((DZ(joystick.joy1_y1))+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[B] = ((((DZ(joystick.joy1_y1))-DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[C] = -((((DZ(joystick.joy1_y1))+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[D] = ((((DZ(joystick.joy1_x1))-DZ(joystick.joy1_y1))/128.0)*100) - turn;

			}else if(direction == "left"){
			motor[B] = ((((DZ(joystick.joy1_y1))+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[C] = ((((DZ(joystick.joy1_y1))-DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[D] = -((((DZ(joystick.joy1_y1))+DZ(joystick.joy1_x1))/128.0)*100) - turn;
			motor[A] = ((((DZ(joystick.joy1_x1))-DZ(joystick.joy1_y1))/128.0)*100) - turn;
		}
		turn = joystick.joy1_x2/10;
	}
}

task main()
{
	initializeRobot();

	StartTask(directionCont);

	StartTask(drive);

	while (true){
	}
}
