#pragma config(Motor,  motorA,          attachment,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          right,         tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

task main()
{
while(1==1)
{
	getJoystickSettings(joystick);
	if (joystick.joy1_y1 < 10 && joystick.joy1_y1 > -10)
	{
		motor [left]=0;
	}
	else
	{
		motor[left]= joystick.joy1_y1;
	}
	if (joystick.joy1_y2 < 10 && joystick.joy1_y2 > -10)
	{
		motor [right]=0;
	}
	else
	{
		motor[right]= joystick.joy1_y2;
	}
	if (joy1Btn(2)==1)
	{
		motor [attachment]= 40;
	}
	if (joy1Btn(4)==1)
	{
		motor [attachment]=-40;
	}
	if (joy1Btn(2)==0 && joy1Btn(4)==0)
	{
		motor [attachment]= 0;
	}
}

}
